### ISSUE TITLE
RESPONSE 400

### ISSUE THREAD

**Issue by teelrabbit** [teelrabbit/ChatGDP-DiscordBot#1]
When using chatGDP Discord bot it will get a response 400 

```
    at settle (/Users/F.Bueller/Documents/GitHub/ChatGDP-DiscordBot/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/F.Bueller/Documents/GitHub/ChatGDP-DiscordBot/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false

**Comment by teelrabbit** [comment]
Temperature spelled wrong and was causing a bad request to the openai api
